<div class="loader"><img src="{{ asset('images/logolight.webp') }}" alt=""><div class="ld-num">0</div></div>
<div class="cursor"></div><div class="cursor-dot"></div>
<header class="nav">
  <div class="nav-in"><div class="nav-bar">
    <a href="{{ route('home') }}" class="brand"><img src="{{ asset('images/logo.webp') }}" alt="Sunfit General Contracting logo"><span><b>SUNFIT</b><small>General Contracting</small></span></a>
    <nav class="links">
      <a @class(['on' => request()->routeIs('home')]) href="{{ route('home') }}">Home</a><a @class(['on' => request()->routeIs('about')]) href="{{ route('about') }}">About</a>
      <div class="has-dd"><a @class(['on' => request()->routeIs('services*')]) href="{{ route('services') }}">Services <svg viewBox="0 0 12 12"><path d="m2 4 4 4 4-4"/></svg></a><div class="dd"><a @class(['on' => request()->routeIs('services.civil-fit-out')]) href="{{ route('services.civil-fit-out') }}"><i><svg viewBox="0 0 24 24"><path d="M2 20h20M4 20V9l8-5 8 5v11M9 20v-6h6v6"/></svg></i>Civil &amp; Fit Out Works<em>01</em></a><a @class(['on' => request()->routeIs('services.mep-works')]) href="{{ route('services.mep-works') }}"><i><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M12 1v3M12 20v3M4.2 4.2l2.1 2.1M17.7 17.7l2.1 2.1M1 12h3M20 12h3M4.2 19.8l2.1-2.1M17.7 6.3l2.1-2.1"/></svg></i>MEP Works<em>02</em></a><a @class(['on' => request()->routeIs('services.demolition-works')]) href="{{ route('services.demolition-works') }}"><i><svg viewBox="0 0 24 24"><path d="M4 20h16M7 20V10l5-4 5 4v10M10 20v-5h4v5"/></svg></i>Demolition Works<em>03</em></a><a @class(['on' => request()->routeIs('services.authority-approvals')]) href="{{ route('services.authority-approvals') }}"><i><svg viewBox="0 0 24 24"><path d="M12 3l8 4v6c0 5-3.4 7.6-8 9-4.6-1.4-8-4-8-9V7z"/></svg></i>Authority Approvals<em>04</em></a></div></div>
      <div class="has-dd"><a @class(['on' => request()->routeIs('projects*')]) href="{{ route('projects.ongoing') }}">Projects <svg viewBox="0 0 12 12"><path d="m2 4 4 4 4-4"/></svg></a><div class="dd"><a @class(['on' => request()->routeIs('projects.ongoing')]) href="{{ route('projects.ongoing') }}"><i><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><path d="M12 8v4l3 2"/></svg></i>Ongoing Projects<em>01</em></a><a @class(['on' => request()->routeIs('projects.completed')]) href="{{ route('projects.completed') }}"><i><svg viewBox="0 0 24 24"><path d="M8 12.5l2.5 2.5L16 9.5"/><circle cx="12" cy="12" r="9"/></svg></i>Completed Projects<em>02</em></a></div></div><a @class(['on' => request()->routeIs('contact')]) href="{{ route('contact') }}">Contact</a>
    </nav>
    <a href="{{ route('contact') }}" class="pill sun">Free Estimate <span class="o"><svg viewBox="0 0 24 24" fill="none" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 5l7 7-7 7"/></svg></span></a>
    <button class="burger" aria-label="Menu"><span></span></button>
  </div></div>
</header>
