<div class="loader"><img src="{{ asset('images/logolight.webp') }}" alt=""><div class="ld-num">0</div></div>
<div class="cursor"></div><div class="cursor-dot"></div>
<header class="nav">
  <div class="nav-in"><div class="nav-bar">
    <a href="{{ route('home') }}" class="brand"><img src="{{ asset('images/logo.webp') }}" alt="Sunfit General Contracting logo"><span><b>SUNFIT</b><small>General Contracting</small></span></a>
    <nav class="links">
      <a @class(['on' => request()->routeIs('home')]) href="{{ route('home') }}">Home</a><a @class(['on' => request()->routeIs('about')]) href="{{ route('about') }}">About</a>
      <div class="has-dd"><a @class(['on' => request()->routeIs('services*')]) href="{{ route('services') }}">Services <svg viewBox="0 0 12 12"><path d="m2 4 4 4 4-4"/></svg></a><div class="dd"><a @class(['on' => request()->routeIs('services.civil-works')]) href="{{ route('services.civil-works') }}"><i><svg viewBox="0 0 24 24"><path d="M2 20h20M4 20V9l8-5 8 5v11M9 20v-6h6v6"/></svg></i>Civil Works<em>01</em></a><a @class(['on' => request()->routeIs('services.structural-works')]) href="{{ route('services.structural-works') }}"><i><svg viewBox="0 0 24 24"><path d="M3 21h18M5 21V3h14v18M5 8h14M5 14h14M10 3v18M14 3v18"/></svg></i>Structural Works<em>02</em></a><a @class(['on' => request()->routeIs('services.electrical-works')]) href="{{ route('services.electrical-works') }}"><i><svg viewBox="0 0 24 24"><path d="M13 2 4 14h7l-1 8 9-12h-7z"/></svg></i>Electrical Works<em>03</em></a><a @class(['on' => request()->routeIs('services.mechanical-works')]) href="{{ route('services.mechanical-works') }}"><i><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M12 1v3M12 20v3M4.2 4.2l2.1 2.1M17.7 17.7l2.1 2.1M1 12h3M20 12h3M4.2 19.8l2.1-2.1M17.7 6.3l2.1-2.1"/></svg></i>Mechanical Works<em>04</em></a><a @class(['on' => request()->routeIs('services.plumbing-works')]) href="{{ route('services.plumbing-works') }}"><i><svg viewBox="0 0 24 24"><path d="M12 2.7s-6 6.3-6 11.3a6 6 0 0 0 12 0c0-5-6-11.3-6-11.3z"/><path d="M9 15a3 3 0 0 0 3 3"/></svg></i>Plumbing Works<em>05</em></a><a @class(['on' => request()->routeIs('services.interior-design-works')]) href="{{ route('services.interior-design-works') }}"><i><svg viewBox="0 0 24 24"><path d="M4 11V8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v3"/><path d="M2 13a2 2 0 0 1 4 0v2h12v-2a2 2 0 0 1 4 0v5H2z"/><path d="M5 18v2M19 18v2"/></svg></i>Interior Designing Works<em>06</em></a></div></div>
      <a @class(['on' => request()->routeIs('projects')]) href="{{ route('projects') }}">Projects</a><a @class(['on' => request()->routeIs('contact')]) href="{{ route('contact') }}">Contact</a>
    </nav>
    <a href="{{ route('contact') }}" class="pill sun">Free Estimate <span class="o"><svg viewBox="0 0 24 24" fill="none" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 5l7 7-7 7"/></svg></span></a>
    <button class="burger" aria-label="Menu"><span></span></button>
  </div></div>
</header>
